live_config_reload = true
import = [
	"~/.config/themes/alacritty-theme/themes/gruvbox_material_hard_dark.toml"
]

[font]
normal = { family = "JetBrainsMonoNerdFontMono", style = "Regular" }
size = 12

[window]
opacity = 0.8
padding = { x = 10, y = 20 }
decorations = "Full"
